### ISSUE TITLE
Ken's Peer Code-Review on 16/09/2022

### ISSUE THREAD

**Issue by Jhaman1895** [Kasaija-Kenneth/mobile_first_portfolio#12]
Here, our morning session team conducted a peer code-review for the latest live-demo of Ken's portfolio project.

**Comment by Jhaman1895** [comment]
I would kindly suggest that you add a gap between your technologies list on the works cards of your mobile version. Otherwise, fantastic effort!

**Comment by NurkaAmre** [comment]
Great work! Nothing to commit.

**Comment by Ngufor-emmanuella** [comment]
great job your work looks great!!

**Comment by kkasaija** [comment]
Thanks to you all, all changes actioned as suggested.
