### ISSUE TITLE
Hide and seek excersise

### ISSUE THREAD

**Issue by ReemMohamedAbdelfatah** [Kasaija-Kenneth/mobile_first_portfolio#15]
Hello @Kasaija-Kenneth ,
Changes required to solve in javascript on popup-branch:
I noticed their is a single quotes inside double quotes on file "script.js" line '7'
please edit it and you are good to proceed the great work .
Happy coding!

**Comment by kkasaija** [comment]
Thanks, all changes made as suggested.
