### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by udev-21** [Kasaija-Kenneth/mobile_first_portfolio#6]
1) This color must be part of the background of your body.
2) Remove these spaces, they don't make your page look pretty.
3) I suggest you add more margin-bottom in this section.
<img src="https://user-images.githubusercontent.com/41912912/188032254-1ac30597-6b3a-40c3-9586-1d37ab1ca1b7.png" >

4) I kindly suggest you correctly position these arrows icons
<img src="https://user-images.githubusercontent.com/41912912/188032428-bd78e809-4304-4c5f-94f4-6734967ffc88.png" >
5) I kindly suggest adjusting the background, here it looks elongated (loses its proportion), try background-size:cover.
<img src="https://user-images.githubusercontent.com/41912912/188032590-c14ce845-5dfa-43cd-9ff9-51b86f5b3329.png">

**Comment by kkasaija** [comment]
Implement all recommended changes
